"""add resource type

Revision ID: 0537c969580e
Revises: ba4694f23a85
Create Date: 2025-08-16 13:27:33.587407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0537c969580e"
down_revision: Union[str, Sequence[str], None] = "ba4694f23a85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("resource", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "resource")
    # ### end Alembic commands ###
