"""add collection permissions

Revision ID: 12a81fee679b
Revises: 8c2bd1b641f3
Create Date: 2025-08-09 20:34:07.137959

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12a81fee679b"
down_revision: Union[str, Sequence[str], None] = "8c2bd1b641f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_permission",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "permission_level",
            sa.Enum("READ", "EDIT", "OWNER", name="collection_permission_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collection.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collection_permission_audit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_permission_id", sa.UUID(), nullable=False),
        sa.Column("performed_by", sa.UUID(), nullable=True),
        sa.Column(
            "performed_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "old_permission",
            sa.Enum("READ", "EDIT", "OWNER", name="collection_permission_enum"),
            nullable=True,
        ),
        sa.Column(
            "new_permission",
            sa.Enum("READ", "EDIT", "OWNER", name="collection_permission_enum"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["collection_permission_id"],
            ["collection_permission.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["performed_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_permission_audit")
    op.drop_table("collection_permission")
    # ### end Alembic commands ###
