"""add_user_ai_preference

Revision ID: 1f94d6f7fc3f
Revises: 237631b63450
Create Date: 2025-08-23 16:09:17.135902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f94d6f7fc3f"
down_revision: Union[str, Sequence[str], None] = "237631b63450"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_ai_preference",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("call", sa.Text(), nullable=True),
        sa.Column("skillset", sa.Text(), nullable=True),
        sa.Column("depth_of_explanation", sa.Text(), nullable=True),
        sa.Column(
            "language_preference", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("stopwords", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_ai_preference")
    # ### end Alembic commands ###
