"""add collection id to documents

Revision ID: 1fc85a0f8c78
Revises: 0537c969580e
Create Date: 2025-08-18 13:27:15.143650

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fc85a0f8c78"
down_revision: Union[str, Sequence[str], None] = "0537c969580e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("collection_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_document_collection_id",
        "document",
        "collection",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_document_collection_id", "document", type_="foreignkey")
    op.drop_column("document", "collection_id")
    # ### end Alembic commands ###
