"""add_unique_constraint_to_collection_ai_preference

Revision ID: befe5f32dce6
Revises: cc331805ccbc
Create Date: 2025-08-29 09:49:00.931067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "befe5f32dce6"
down_revision: Union[str, Sequence[str], None] = "cc331805ccbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "collection_ai_preference", ["collection_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "collection_ai_preference", type_="unique")
    # ### end Alembic commands ###
